// lib/commands/index.js — 命令注册表

module.exports = {
  search: require('./search'),
  get: require('./get'),
  replies: require('./replies'),
  my: require('./my'),
  user: require('./user'),
  post: require('./post'),
  like: require('./like'),
  'delete-comment': require('./delete-comment'),
  download: require('./download'),
  analyze: require('./analyze'),
  suggest: require('./suggest'),
  dashboard: require('./dashboard'),
  log: require('./log'),
  profile: require('./profile'),
  events: require('./events'),
  whois: require('./whois'),
  note: require('./note'),
  corpus: require('./corpus'),
  failures: require('./failures'),
  dedup: require('./dedup'),
  replied: require('./replied'),
  dm: require('./dm'),
  cleanup: require('./cleanup'),
  browse: require('./browse'),
};
